package keccak256

import (
	"golang.org/x/crypto/sha3"
)

const _hashlength = 32

// Keccak256 is the Keccak-256 hashing method
type Keccak256 struct{}

// New creates a new Keccak-256 hashing method
func New() *Keccak256 {
	return &Keccak256{}
}

// HashLength returns the length of hashes generated by Hash() in bytes
func (h *Keccak256) HashLength() int {
	return _hashlength
}

// Hash generates a Keccak-256 hash from a byte array
func (h *Keccak256) Hash(data ...[]byte) []byte {
	hash := sha3.NewLegacyKeccak256()
	for _, d := range data {
		hash.Write(d)
	}
	return hash.Sum(nil)[:4]
}
